### ISSUE TITLE
Cannot parse async/await

### ISSUE THREAD

**Issue by JennieJi** [kategengler/ember-cli-code-coverage#106]

**Comment by sukima** [comment]
**No! why was this closed?!**

This is breaking our builds!

```console
Failed to parse file: app/components/my-component.js
Unable to cover: app/components/my-component.js . Try setting useBabelInstrumenter to true.
 Error: Line 66: Unexpected identifier
  at constructError (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:2407:21)
  at createError (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:2426:17)
  at unexpectedTokenError (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:2500:13)
  at throwUnexpectedToken (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:2505:15)
  at expect (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:2523:13)
  at expectCommaSeparator (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:2547:13)
  at parseObjectInitializer (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:3053:17)
  at inheritCoverGrammar (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:2681:18)
  at parsePrimaryExpression (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:3247:20)
  at inheritCoverGrammar (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:2681:18)
  at parseLeftHandSideExpressionAllowCall (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:3414:20)
  at inheritCoverGrammar (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:2681:18)
  at parsePostfixExpression (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:3490:16)
  at parseUnaryExpression (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:3550:20)
  at inheritCoverGrammar (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:2681:18)
  at parseBinaryExpression (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:3639:16)
  at inheritCoverGrammar (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:2681:18)
  at parseConditionalExpression (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:3696:16)
  at parseAssignmentExpression (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:3893:16)
  at isolateCoverGrammar (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:2663:18)
  at parseArguments (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:3327:28)
  at parseLeftHandSideExpressionAllowCall (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:3426:24)
  at inheritCoverGrammar (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:2681:18)
  at parsePostfixExpression (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:3490:16)
  at parseUnaryExpression (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:3519:20)
  at inheritCoverGrammar (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:2681:18)
  at parseBinaryExpression (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:3639:16)
  at inheritCoverGrammar (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:2681:18)
  at parseConditionalExpression (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:3696:16)
  at parseAssignmentExpression (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:3893:16)
  at parseExportDefaultDeclaration (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:5313:26)
  at parseExportDeclaration (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:5345:20)
  at parseStatementListItem (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:3970:24)
  at parseScriptBody (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:5490:25)
  at parseProgram (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:5506:16)
  at Object.parse (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:5690:23)
  at Object.instrumentSync (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/lib/instrumenter.js:459:31)
  at CoverageInstrumenter.processString (/Users/suki/source/SeeClickFix/partners/node_modules/ember-cli-code-coverage/lib/coverage-instrumenter.js:113:25)
  at CoverageInstrumenter.processFile (/Users/suki/source/SeeClickFix/partners/node_modules/broccoli-filter/index.js:165:31)
  at asyncProcessFile (/Users/suki/source/SeeClickFix/partners/node_modules/broccoli-filter/index.js:122:21)
  at tryCatch (/Users/suki/source/SeeClickFix/partners/node_modules/rsvp/dist/rsvp.js:539:12)
  at invokeCallback (/Users/suki/source/SeeClickFix/partners/node_modules/rsvp/dist/rsvp.js:554:13)
  at /Users/suki/source/SeeClickFix/partners/node_modules/rsvp/dist/rsvp.js:629:16
  at flush (/Users/suki/source/SeeClickFix/partners/node_modules/rsvp/dist/rsvp.js:2414:5)
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by JennieJi** [comment]
@sukima I figured out that settings are needed to support this after read documents carefully.  
That is, add **coverage.js** to **/config** folder, and following is the content of it:  
```js
module.exports = {
  useBabelInstrumenter: true
};
```

**Comment by rwjblue** [comment]
FWIW, the error message says **exactly** that 😸 

> Unable to cover: app/components/my-component.js . Try setting useBabelInstrumenter to true.

**Comment by sukima** [comment]
So I didn't do that because I didn't care about instrumentation of the error. Isn't that option for better error messages? I'm confused.

Cognitive confusion: _Try setting useBabelInstrumenter to true._ does not offer any clue that it enables async await (or enables anything related to the program being stupid) If it was called `enableES7` or `enableNotStupidMode` I think I would have understood.

**Comment by rwjblue** [comment]
LOL, I agree that the error message could be better, would you mind submitting a pull request to tweak it?
