### ISSUE TITLE
Parsing async/await crashes

### ISSUE THREAD

**Issue by sukima** [kategengler/ember-cli-code-coverage#108]
This appears related to a old version of istanbul: https://github.com/gotwarlost/istanbul/issues/733

```console
Failed to parse file: app/components/my-component.js
Unable to cover: app/components/my-component.js . Try setting useBabelInstrumenter to true.
 Error: Line 66: Unexpected identifier
  at constructError (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:2407:21)
  at createError (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:2426:17)
  at unexpectedTokenError (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:2500:13)
  at throwUnexpectedToken (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:2505:15)
  at expect (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:2523:13)
  at expectCommaSeparator (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:2547:13)
  at parseObjectInitializer (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:3053:17)
  at inheritCoverGrammar (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:2681:18)
  at parsePrimaryExpression (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:3247:20)
  at inheritCoverGrammar (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:2681:18)
  at parseLeftHandSideExpressionAllowCall (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:3414:20)
  at inheritCoverGrammar (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:2681:18)
  at parsePostfixExpression (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:3490:16)
  at parseUnaryExpression (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:3550:20)
  at inheritCoverGrammar (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:2681:18)
  at parseBinaryExpression (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:3639:16)
  at inheritCoverGrammar (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:2681:18)
  at parseConditionalExpression (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:3696:16)
  at parseAssignmentExpression (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:3893:16)
  at isolateCoverGrammar (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:2663:18)
  at parseArguments (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:3327:28)
  at parseLeftHandSideExpressionAllowCall (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:3426:24)
  at inheritCoverGrammar (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:2681:18)
  at parsePostfixExpression (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:3490:16)
  at parseUnaryExpression (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:3519:20)
  at inheritCoverGrammar (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:2681:18)
  at parseBinaryExpression (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:3639:16)
  at inheritCoverGrammar (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:2681:18)
  at parseConditionalExpression (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:3696:16)
  at parseAssignmentExpression (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:3893:16)
  at parseExportDefaultDeclaration (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:5313:26)
  at parseExportDeclaration (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:5345:20)
  at parseStatementListItem (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:3970:24)
  at parseScriptBody (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:5490:25)
  at parseProgram (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:5506:16)
  at Object.parse (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/node_modules/esprima/esprima.js:5690:23)
  at Object.instrumentSync (/Users/suki/source/SeeClickFix/partners/node_modules/istanbul/lib/instrumenter.js:459:31)
  at CoverageInstrumenter.processString (/Users/suki/source/SeeClickFix/partners/node_modules/ember-cli-code-coverage/lib/coverage-instrumenter.js:113:25)
  at CoverageInstrumenter.processFile (/Users/suki/source/SeeClickFix/partners/node_modules/broccoli-filter/index.js:165:31)
  at asyncProcessFile (/Users/suki/source/SeeClickFix/partners/node_modules/broccoli-filter/index.js:122:21)
  at tryCatch (/Users/suki/source/SeeClickFix/partners/node_modules/rsvp/dist/rsvp.js:539:12)
  at invokeCallback (/Users/suki/source/SeeClickFix/partners/node_modules/rsvp/dist/rsvp.js:554:13)
  at /Users/suki/source/SeeClickFix/partners/node_modules/rsvp/dist/rsvp.js:629:16
  at flush (/Users/suki/source/SeeClickFix/partners/node_modules/rsvp/dist/rsvp.js:2414:5)
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by sukima** [comment]
This is a duplicate of #106 simply because others cannot reopen issues.

**Comment by rwjblue** [comment]
Did you try doing what the error message instructs you to do?

**Comment by sukima** [comment]
Yes, This does not work. ember-ajax (included by ember by default) crashes:

```console
File: ember-ajax/ajax-request.js
The Broccoli Plugin: [broccoli-persistent-filter:Babel] failed with:
ReferenceError: [BABEL] ember-ajax/ajax-request.js: Unknown option: direct.useBabelInstrumenter
  at Logger.error (/Users/suki/source/SeeClickFix/partners/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
  at OptionManager.mergeOptions (/Users/suki/source/SeeClickFix/partners/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
  at OptionManager.init (/Users/suki/source/SeeClickFix/partners/node_modules/babel-core/lib/transformation/file/options/option-manager.js:216:10)
  at File.initOptions (/Users/suki/source/SeeClickFix/partners/node_modules/babel-core/lib/transformation/file/index.js:147:75)
  at new File (/Users/suki/source/SeeClickFix/partners/node_modules/babel-core/lib/transformation/file/index.js:137:22)
  at Pipeline.transform (/Users/suki/source/SeeClickFix/partners/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
```

**Comment by rwjblue** [comment]
The option is for `config/coverage.js`, it has nothing to do with your applications babel configuration itself.

**Comment by sukima** [comment]
![Doh'](http://mets360.com/wp-content/uploads/2015/08/homer-doh.png)
