### ISSUE TITLE
Coverage for in-repo-addons not working

### ISSUE THREAD

**Issue by thiagofesta** [kategengler/ember-cli-code-coverage#120]
You can reproduce the problem using this repo: https://github.com/thiagofesta/test-coverage
```
$ COVERAGE=true ember test
```

It gives me this error:
```
this.parent.name is not a function
TypeError: this.parent.name is not a function
    at Class.module.exports._parentName (/Users/tfesta/Code/test-coverage/node_modules/ember-cli-code-coverage/index.js:244:26)
    at Class.module.exports._getExcludes (/Users/tfesta/Code/test-coverage/node_modules/ember-cli-code-coverage/index.js:216:21)
    at Class.module.exports.preprocessTree (/Users/tfesta/Code/test-coverage/node_modules/ember-cli-code-coverage/index.js:48:21)
    at /Users/tfesta/Code/test-coverage/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25
    at Array.reduce (native)
    at addonProcessTree (/Users/tfesta/Code/test-coverage/node_modules/ember-cli/lib/utilities/addon-process-tree.js:4:32)
    at Class._addonPreprocessTree (/Users/tfesta/Code/test-coverage/node_modules/ember-cli/lib/models/addon.js:378:12)
    at Class.processedAddonJsFiles (/Users/tfesta/Code/test-coverage/node_modules/ember-cli/lib/models/addon.js:1133:36)
    at Class.compileAddon (/Users/tfesta/Code/test-coverage/node_modules/ember-cli/lib/models/addon.js:1048:24)
    at Class.treeForAddon (/Users/tfesta/Code/test-coverage/node_modules/ember-cli/lib/models/addon.js:707:26)
```

I also had another problem earlier, where it complained about `isEmberCLIAddon` method not defined. What i did, was to create that method on the in repo addon and return false. But by default it is not generated by ember cli, maybe you could assume if it is undefined, use it as false.

Thanks

**Comment by rwjblue** [comment]
Thank you reporting! I'll try to dig into the demo soon and see how hard it will be to fix...

**Comment by thiagofesta** [comment]
@rwjblue any updates on this one?

**Comment by GCheung55** [comment]
PR #107 tried to address this but there are test errors.

**Comment by rwjblue** [comment]
https://github.com/kategengler/ember-cli-code-coverage/pull/141 should make this a bit easier to do, but is still somewhat WIP.  I believe that the changes @GCheung55 submitted in #107 will come in handy in that branch...

**Comment by rwwagner90** [comment]
I believe this works as of the latest beta. Can you guys try it out?
<img width="1680" alt="screen shot 2018-02-02 at 12 21 33 am" src="https://user-images.githubusercontent.com/2640861/35717770-3891a856-07af-11e8-84cd-484706837405.png">

**Comment by rwwagner90** [comment]
Closing this, as it should be fixed in the latest beta. If not, feel free to reopen!
