### ISSUE TITLE
useBabelInstrumenter don't works

### ISSUE THREAD

**Issue by villander** [kategengler/ember-cli-code-coverage#193]
ember-cli: 3.3.0

I create the config/converage.js like this:

```js
module.exports = {
  useBabelInstrumenter: true
};
```

but the errors continue

```
Unable to cover: app/utils/paycertify-highcharts-theme.js . Newer JS features may need Babel instrumentation to work. Try setting useBabelInstrumenter to true in your config/coverage.js.
 Error: Plugin 0 specified in "base" provided an invalid property of "_parallelBabel"
    at Plugin.init (/Users/villander/Projects/web_app/node_modules/babel-core/lib/transformation/plugin.js:131:13)
    at Function.normalisePlugin (/Users/villander/Projects/web_app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:152:12)
    at /Users/villander/Projects/web_app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (<anonymous>:null:null)
    at Function.normalisePlugins (/Users/villander/Projects/web_app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/villander/Projects/web_app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/villander/Projects/web_app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/villander/Projects/web_app/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/villander/Projects/web_app/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/villander/Projects/web_app/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at Instrumenter.instrumentSync (/Users/villander/Projects/web_app/node_modules/ember-cli-code-coverage/lib/babel-istanbul-instrumenter.js:44:45)
    at CoverageInstrumenter.processString (/Users/villander/Projects/web_app/node_modules/ember-cli-code-coverage/lib/coverage-instrumenter.js:112:25)
    at CoverageInstrumenter.processFile (/Users/villander/Projects/web_app/node_modules/broccoli-filter/index.js:165:31)
    at asyncProcessFile (/Users/villander/Projects/web_app/node_modules/broccoli-filter/index.js:122:21)
    at tryCatch (/Users/villander/Projects/web_app/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/villander/Projects/web_app/node_modules/rsvp/dist/rsvp.js:538:13)
    at /Users/villander/Projects/web_app/node_modules/rsvp/dist/rsvp.js:606:14
    at flush (/Users/villander/Projects/web_app/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by villander** [comment]
cc: @rwjblue @kategengler

**Comment by kategengler** [comment]
Please try the latest 1.0 beta of this addon (1.0.0-beta.5)

**Comment by villander** [comment]
it's solved my issue, thanks @kategengler
