### ISSUE TITLE
Not compatible with babel 7?

### ISSUE THREAD

**Issue by luketheobscure** [kategengler/ember-cli-code-coverage#215]
In the process of getting a small app updated to the newest version of everything. Everything works, but when I add `COVERAGE=true` I'm now getting complaints from ember-cli-code-coverage:

```
Unable to cover: app/app.js . Newer JS features may need Babel instrumentation to work. Try setting useBabelInstrumenter to true in your config/coverage.js.
 Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
    at throwVersionError (/Users/{redacted}/node_modules/@babel/helper-plugin-utils/lib/index.js:65:11)
    at Object.assertVersion (/Users/{redacted}/node_modules/@babel/helper-plugin-utils/lib/index.js:13:11)
    at _default (/Users/{redacted}/node_modules/@babel/plugin-proposal-decorators/lib/index.js:43:7)
    at /Users/{redacted}/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at Function.memoisePluginContainer (/Users/{redacted}/node_modules/babel-core/lib/transformation/file/options/option-manager.js:113:13)
    at Function.normalisePlugin (/Users/{redacted}/node_modules/babel-core/lib/transformation/file/options/option-manager.js:146:32)
    at /Users/{redacted}/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (<anonymous>:null:null)
    at Function.normalisePlugins (/Users/{redacted}/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/{redacted}/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/{redacted}/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/{redacted}/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/{redacted}/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/{redacted}/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at Instrumenter.instrumentSync (/Users/{redacted}/node_modules/ember-cli-code-coverage/lib/babel-istanbul-instrumenter.js:44:45)
    at CoverageInstrumenter.processString (/Users/{redacted}/node_modules/ember-cli-code-coverage/lib/coverage-instrumenter.js:112:25)
    at CoverageInstrumenter.processFile (/Users/{redacted}/node_modules/broccoli-filter/index.js:165:31)
    at asyncProcessFile (/Users/{redacted}/node_modules/broccoli-filter/index.js:122:21)
    at tryCatch (/Users/{redacted}/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/{redacted}/node_modules/rsvp/dist/rsvp.js:538:13)
    at /Users/{redacted}/node_modules/rsvp/dist/rsvp.js:606:14
    at flush (/Users/{redacted}/node_modules/rsvp/dist/rsvp.js:2415:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

Here's what I think are the relevant bits of my package.json:
```
"devDependencies": {
    "@ember-decorators/babel-transforms": "^2.0.0",
    "ember-auto-import": "^1.2.21",
    "ember-cli": "~3.8.1",
    "ember-cli-babel": "^7.6.0",
    "ember-cli-bourbon": "^2.0.1",
    "ember-cli-code-coverage": "^0.4.2",
    "ember-cli-qunit": "^4.3.2",
    "ember-cli-template-lint": "^1.0.0-beta.1",
    "ember-data": "~3.8.0",
    "ember-export-application-global": "^2.0.0",
    "ember-resolver": "^5.1.3",
    "ember-source": "~3.8.0",
    "loader.js": "^4.7.0",
  },
  "dependencies": {
    "ember-component-css": "^0.6.7",
    "ember-decorators": "^2.5.1",
  },
```

I do have `useBabelInstrumenter: true` in my `config/coverage.js` file.

**Comment by luketheobscure** [comment]
Just upgraded from ember-cli-code-coverage
 0.4.2 to 1.0.0-beta.8 and everything seems to be working fine!

**Comment by safirelauene** [comment]
I'm having same problem. :disappointed: 
Using ember-cli-code-coverage 1.0.3
```Build failed.
Build Error (Analyzer)

Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a 
compatible version of @babel/core, it is likely that something in your build process is 
loading the wrong version. Inspect the stack trace of this error to look for the first entry 
that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
```
