### ISSUE TITLE
coverage fails with ember-decorators

### ISSUE THREAD

**Issue by 0xadada** [kategengler/ember-cli-code-coverage#216]
I recently added `ember-decorators` to my project, and converted a single model and a single component to native ES classes with decorators. After doing this, my code coverage stopped working, throwing errors.

I've posted a minimal reproduction repo here:
https://github.com/0xadada/sandbox-native-classes-code-coverage

**before**
```javascript
// app/models/author.js
import DS from 'ember-data';
const { Model, attr } = DS;

export default Model.extend({
  name: attr('string')
});
```

**after**
```javascript
// app/models/author.js
import DS from 'ember-data';
import { attr } from '@ember-decorators/data';
const { Model } = DS;

export default class AuthorModel extends Model {
  @attr('string')
  name
}
```

**before**
```javascript
import Component from '@ember/component';
import { computed } from '@ember/object';

export default Component.extend({
  name: computed('model.name.length', function() {
    if(this.model.name.length) {
      return `${this.model._internalModel.clientId} / ${this.model.name}`;
    } else {
      return `no name`;
    }
  })
});
```
**after**
```javascript
// app/components/author.js
import Component from '@ember/component';
import { computed } from '@ember-decorators/object';

export default class AuthorComponent extends Component {
  @computed('model.name.length')
  get name() {
    if(this.model.name.length) {
      return `${this.model._internalModel.clientId} / ${this.model.name}`;
    } else {
      return `no name`;
    }
  }
}
```

When i run my app and run `ember test`, both work great. When I run tests with `COVERAGE=true`, it fails with the following errors:

```bash
$ COVERAGE=true ember test
WARNING: sandbox-native-classes-code-coverage has added the decorators plugin to its build, but ember-cli-babel provides these by default now! You can remove the transforms, or the addon that provided them, such as @ember-decorators/babel-transforms. Ember supports the stage 1 decorator spec and transforms, so if you were using stage 2, you'll need to ensure that your decorators are compatible, or convert them to stage 1.
WARNING: sandbox-native-classes-code-coverage has added the class-properties plugin to its build, but ember-cli-babel provides these by default now! You can remove the transforms, or the addon that provided them, such as @ember-decorators/babel-transforms.
WARNING: sandbox-native-classes-code-coverage has added the decorators plugin to its build, but ember-cli-babel provides these by default now! You can remove the transforms, or the addon that provided them, such as @ember-decorators/babel-transforms. Ember supports the stage 1 decorator spec and transforms, so if you were using stage 2, you'll need to ensure that your decorators are compatible, or convert them to stage 1.
WARNING: sandbox-native-classes-code-coverage has added the class-properties plugin to its build, but ember-cli-babel provides these by default now! You can remove the transforms, or the addon that provided them, such as @ember-decorators/babel-transforms.
Environment: test
Circular dependency: ../../../../var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-8561unb8YAq2hqHg/cache-079-rollup/build/-private/system/model/model.js -> ../../../../var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-8561unb8YAq2hqHg/cache-079-rollup/build/-private/system/model/internal-model.js -> ../../../../var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-8561unb8YAq2hqHg/cache-079-rollup/build/-private/system/references.js -> ../../../../var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-8561unb8YAq2hqHg/cache-079-rollup/build/-private/system/references/belongs-to.js -> ../../../../var/folders/1t/rw1tf_f56zq4qc9mnvk38xrr0000gn/T/broccoli-8561unb8YAq2hqHg/cache-079-rollup/build/-private/system/model/model.js
Failed to parse file: app/components/author.js
Unable to cover: app/components/author.js . Newer JS features may need Babel instrumentation to work. Try setting useBabelInstrumenter to true in your config/coverage.js.
 Error: Line 6: Unexpected token ILLEGAL
    at constructError (/Users/0xadada/0xadada/sandbox-native-classes-code-coverage/node_modules/istanbul/node_modules/esprima/esprima.js:2407:21)
    at createError (/Users/0xadada/0xadada/sandbox-native-classes-code-coverage/node_modules/istanbul/node_modules/esprima/esprima.js:2426:17)
    at unexpectedTokenError (/Users/0xadada/0xadada/sandbox-native-classes-code-coverage/node_modules/istanbul/node_modules/esprima/esprima.js:2501:13)
    at throwUnexpectedToken (/Users/0xadada/0xadada/sandbox-native-classes-code-coverage/node_modules/istanbul/node_modules/esprima/esprima.js:2505:15)
    at scanPunctuator (/Users/0xadada/0xadada/sandbox-native-classes-code-coverage/node_modules/istanbul/node_modules/esprima/esprima.js:842:13)
    at advance (/Users/0xadada/0xadada/sandbox-native-classes-code-coverage/node_modules/istanbul/node_modules/esprima/esprima.js:1622:16)
    at lex (/Users/0xadada/0xadada/sandbox-native-classes-code-coverage/node_modules/istanbul/node_modules/esprima/esprima.js:1691:78)
    at expect (/Users/0xadada/0xadada/sandbox-native-classes-code-coverage/node_modules/istanbul/node_modules/esprima/esprima.js:2521:21)
    at parseClassBody (/Users/0xadada/0xadada/sandbox-native-classes-code-coverage/node_modules/istanbul/node_modules/esprima/esprima.js:5094:9)
    at parseClassDeclaration (/Users/0xadada/0xadada/sandbox-native-classes-code-coverage/node_modules/istanbul/node_modules/esprima/esprima.js:5169:21)
Failed to parse file: app/models/author.js
Unable to cover: app/models/author.js . Newer JS features may need Babel instrumentation to work. Try setting useBabelInstrumenter to true in your config/coverage.js.
 Error: Line 7: Unexpected token ILLEGAL
    at constructError (/Users/0xadada/0xadada/sandbox-native-classes-code-coverage/node_modules/istanbul/node_modules/esprima/esprima.js:2407:21)
    at createError (/Users/0xadada/0xadada/sandbox-native-classes-code-coverage/node_modules/istanbul/node_modules/esprima/esprima.js:2426:17)
    at unexpectedTokenError (/Users/0xadada/0xadada/sandbox-native-classes-code-coverage/node_modules/istanbul/node_modules/esprima/esprima.js:2501:13)
    at throwUnexpectedToken (/Users/0xadada/0xadada/sandbox-native-classes-code-coverage/node_modules/istanbul/node_modules/esprima/esprima.js:2505:15)
    at scanPunctuator (/Users/0xadada/0xadada/sandbox-native-classes-code-coverage/node_modules/istanbul/node_modules/esprima/esprima.js:842:13)
    at advance (/Users/0xadada/0xadada/sandbox-native-classes-code-coverage/node_modules/istanbul/node_modules/esprima/esprima.js:1622:16)
    at lex (/Users/0xadada/0xadada/sandbox-native-classes-code-coverage/node_modules/istanbul/node_modules/esprima/esprima.js:1691:78)
    at expect (/Users/0xadada/0xadada/sandbox-native-classes-code-coverage/node_modules/istanbul/node_modules/esprima/esprima.js:2521:21)
    at parseClassBody (/Users/0xadada/0xadada/sandbox-native-classes-code-coverage/node_modules/istanbul/node_modules/esprima/esprima.js:5094:9)
    at parseClassDeclaration (/Users/0xadada/0xadada/sandbox-native-classes-code-coverage/node_modules/istanbul/node_modules/esprima/esprima.js:5169:21)
cleaning up...
Built project successfully. Stored in "/Users/0xadada/0xadada/sandbox-native-classes-code-coverage/tmp/class-tests_dist-kBg0JNa7.tmp".
not ok 1 Chrome 73.0 - [undefined ms] - Global error: Uncaught Error:  Expected to find: 'component:author' within 'sandbox-native-classes-code-coverage/components/author' but got 'undefined'. Did you forget to 'export default' within 'sandbox-native-classes-code-coverage/components/author'? at http://localhost:7357/assets/vendor.js, line 81148
 While executing test: Integration | Component | author: it renders
    ---
        Log: |
            { type: 'error',
              testContext:
               { id: 1,
                 name: 'Integration | Component | author: it renders',
                 items: [],
                 state: 'executing' },
              text:
               'Uncaught Error:  Expected to find: \'component:author\' within \'sandbox-native-classes-code-coverage/components/author\' but got \'undefined\'. Did you forget to \'export default\' within \'sandbox-native-classes-code-coverage/components/author\'? at http://localhost:7357/assets/vendor.js, line 81148\n' }
    ...
not ok 2 Chrome 73.0 - [207 ms] - Integration | Component | author: it renders
    ---
        actual: >
            null
        stack: >
            http://localhost:7357/assets/vendor.js:81148
        message: >
            Uncaught Error:  Expected to find: 'component:author' within 'sandbox-native-classes-code-coverage/components/author' but got 'undefined'. Did you forget to 'export default' within 'sandbox-native-classes-code-coverage/components/author'?
        negative: >
            false
        Log: |
    ...
<edited>
not ok 16 Chrome 73.0 - [46 ms] - Unit | Model | author: it exists
    ---
        actual: >
            null
        stack: >
            Error:  Expected to find: 'model:author' within 'sandbox-native-classes-code-coverage/models/author' but got 'undefined'. Did you forget to 'export default' within 'sandbox-native-classes-code-coverage/models/author'?
                at Class.resolveOther (http://localhost:7357/assets/vendor.js:81148:15)
                at Class.resolve (http://localhost:7357/assets/vendor.js:81205:25)
                at _resolve (http://localhost:7357/assets/vendor.js:1716:42)
                at Registry.resolve (http://localhost:7357/assets/vendor.js:1315:27)
                at Registry.resolve (http://localhost:7357/assets/vendor.js:1319:63)
                at _factoryFor (http://localhost:7357/assets/vendor.js:932:42)
                at Container.factoryFor (http://localhost:7357/assets/vendor.js:866:20)
                at Class.factoryFor (http://localhost:7357/assets/vendor.js:23640:33)
                at _lookupModelFactory (http://localhost:7357/assets/vendor.js:73026:20)
                at getModelFactory (http://localhost:7357/assets/vendor.js:72994:17)
        message: >
            Died on test #1     at Object.<anonymous> (http://localhost:7357/assets/tests.js:109:21)
                at processModule (http://localhost:7357/assets/test-support.js:3609:16)
                at module$1 (http://localhost:7357/assets/test-support.js:3634:4)
                at Module.callback (http://localhost:7357/assets/tests.js:106:21)
                at Module.exports (http://localhost:7357/assets/vendor.js:111:32)
                at requireModule (http://localhost:7357/assets/vendor.js:32:18)
                at TestLoader.require (http://localhost:7357/assets/test-support.js:11400:9):  Expected to find: 'model:author' within 'sandbox-native-classes-code-coverage/models/author' but got 'undefined'. Did you forget to 'export default' within 'sandbox-native-classes-code-coverage/models/author'?
        negative: >
            false
        Log: |
    ...
<edited>

1..18
# tests 18
# pass  15
# skip  0
# fail  3
Testem finished with non-zero exit code. Tests failed.
```

ember / ember cli stuffs
```bash
$ ember --version --verbose
ember-cli: 3.7.1
http_parser: 2.8.0
node: 10.15.3
v8: 6.8.275.32-node.51
uv: 1.23.2
zlib: 1.2.11
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0j
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
os: darwin x64
```

```javascript
// config/coverage.js
'use strict';

module.exports = {
  useBabelInstrumenter: true
};
```
If i restore the above model and component to the _before_ state without ES classes and decorators, it works, but i'd like to use the new hotness.

**Comment by rwwagner90** [comment]
@0xadada have you tried setting `useBabelInstrumenter` to `true` in your config/coverage.js?

**Comment by 0xadada** [comment]
@rwwagner90 yup, tried that, it didn't work.
```javascript
// config/coverage.js
'use strict';

module.exports = {
  useBabelInstrumenter: true
};
```

**Comment by mattmarcum** [comment]
I was running into a similar issue on a new repo and I did a couple of things and got this working - not sure which fixed it...but here's two of them:

update package.json with `    "ember-cli-code-coverage": "1.0.0-beta.8",`

and

update ember-cli-build.js with 
```module.exports = function(defaults) {
  let app = new EmberApp(defaults, {
    babel: {
      sourceMaps: 'inline'
    },

    sourcemaps: {
      enabled: true,
      extensions: ['js']
    },```

**Comment by jrock2004** [comment]
I am getting this which is a little different error. I tried what @mattmarcum suggested above and I get the same results

```
Unable to cover: app/serializers/schedule.js . Newer JS features may need Babel instrumentation to work. Try setting useBabelInstrumenter to true in your config/coverage.js.
 SyntaxError: app/serializers/schedule.js: Unexpected token (4:0)
  2 | import ApplicationSerializer from './application';
  3 |
> 4 | @classic
    | ^
  5 | export default class Schedule extends ApplicationSerializer {
  6 |   primaryKey = 'WeekdayID';
  7 |
    at Parser.pp$5.raise (/myapp/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/myapp/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$1.parseDecorator (/myapp/node_modules/babylon/lib/index.js:1939:10)
    at Parser.pp$1.parseDecorators (/myapp/node_modules/babylon/lib/index.js:1924:26)
    at Parser.pp$1.parseStatement (/myapp/node_modules/babylon/lib/index.js:1818:10)
    at Parser.pp$1.parseBlockBody (/myapp/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseTopLevel (/myapp/node_modules/babylon/lib/index.js:1778:8)
    at Parser.parse (/myapp/node_modules/babylon/lib/index.js:1673:17)
    at parse (/myapp/node_modules/babylon/lib/index.js:7305:37)
    at File.parse (/myapp/node_modules/babel-core/lib/transformation/file/index.js:485:15)
```

**Comment by reiallenramos** [comment]
ran into the same issue and updating the package to a a beta release did the trick.

` "ember-cli-code-coverage": "1.0.0-beta.9"` then `npm install ember-cli-code-coverage`

**Comment by rwwagner90** [comment]
Sounds like this should be fixed now then! If not, please let us know.
