### ISSUE TITLE
`babel-plugin-istanbul` invocation is preventing `ember-cli-babel` from parallelizing

### ISSUE THREAD

**Issue by Turbo87** [kategengler/ember-cli-code-coverage#217]
```
Error: [broccoli-persistent-filter:Babel > [Babel: xxx]: [Babel: xxx] was configured to `throwUnlessParallelizable` and was unable to parallelize a plugin. 
plugins:
1: name: makeVisitor, location: /builds/tobias.bieniek/xxx/node_modules/babel-plugin-istanbul

Please see: https://github.com/babel/broccoli-babel-transpiler#parallel-transpilation for more details
    at new Babel (/builds/tobias.bieniek/xxx/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/index.js:84:13)
    at Class.transpileTree (/builds/tobias.bieniek/xxx/node_modules/ember-cli-babel/index.js:54:16)
```

I suspect using `require.resolve()` instead of `require()` might be able to fix this, similar to https://github.com/ef4/ember-auto-import/pull/199

/cc @stefanpenner @rwjblue

**Comment by Turbo87** [comment]
looks like this was resolved by 77aad94cea2c7820b85e393f9a4f0e7791b0008e. thanks @rwjblue!
