### ISSUE TITLE
Work with ember test --server, not with ember test

### ISSUE THREAD

**Issue by stripedpumpkin** [kategengler/ember-cli-code-coverage#57]
Works fine with `ember test --server` (testem, qunit)

testem.js

```
/*jshint node:true*/
module.exports = {
  "framework": "qunit",
  "test_page": "tests/index.html?hidepassed",
  "disable_watching": true,
  "launch_in_ci": [
    "PhantomJS"
  ],
  "launch_in_dev": [
    "PhantomJS",
    "Chrome"
  ]
};
```

With `ember test`

```
# tests 1272
# pass  1272
# skip  0
# fail  0

# ok
Error: request aborted
    at IncomingMessage.onAborted (/home/office/myapp/frontend/node_modules/ember-cli-code-coverage/node_modules/body-parser/node_modules/raw-body/index.js:269:10)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at abortIncoming (_http_server.js:283:11)
    at Socket.serverSocketCloseListener (_http_server.js:296:5)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:493:12)
```

Is this expected?

```
    "ember-cli": "2.8.0",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-babel": "^5.1.6",
    "ember-cli-chart": "3.1.0",
    "ember-cli-code-coverage": "0.3.4",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-htmlbars": "^1.0.3",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-inject-live-reload": "^1.4.0",
    "ember-cli-jshint": "^1.0.0",
    "ember-cli-moment-shim": "2.2.1",
    "ember-cli-qunit": "^2.1.0"
```

**Comment by kategengler** [comment]
This should be fixed by #82

**Comment by acorncom** [comment]
@stripedpumpkin Does the above PR fix your issue?

**Comment by stripedpumpkin** [comment]
@acorncom Yes, it fixed it.
