### ISSUE TITLE
new error in 0.3.7

### ISSUE THREAD

**Issue by kellyselden** [kategengler/ember-cli-code-coverage#65]
I'm testing out the difference between 0.3.5 and 0.3.7 in my app. 0.3.5 generates the coverage folder. 0.3.6 threw on requiring invalid files. 0.3.7 doesn't generate the coverage folder, and shows this at the end of the console:

```
1..1258
# tests 1258
# pass  1237
# skip  21
# fail  0

# ok
Error
    at IncomingMessage.onAborted (/my-project/node_modules/raw-body/index.js:269:10)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at abortIncoming (_http_server.js:284:11)
    at Socket.serverSocketCloseListener (_http_server.js:297:5)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:501:12)
```

**Comment by kellyselden** [comment]
```
ember-cli: 2.9.1
node: 7.0.0
os: darwin x64
```

**Comment by rwjblue** [comment]
Hmm, definitely odd. The only real differences in 0.3.5 and 0.3.7 are the requiring of additional modules ([diff here](https://github.com/kategengler/ember-cli-code-coverage/compare/v0.3.5...v0.3.7)).  Can you run package-hint-historic-resolver and see if there was another package updated?

**Comment by kellyselden** [comment]
It wasn't an update over time. It was me just now switching between the two versions back and forth.

**Comment by kellyselden** [comment]
Could the requiring of some new random file, that network requests, and fails, and aborts the coverage?

**Comment by rwjblue** [comment]
Definitely possible, but its unlikely that we can help you debug that...

**Comment by kellyselden** [comment]
very true. the problem was just a stab in the dark. If no one else has the issue we should close.

**Comment by thagul** [comment]
I've just ran into the same issue. Any hint on how to debug the issue?

```
1..689
# tests 689
# pass  689
# skip  0
# fail  0

# ok
Error
    at IncomingMessage.onAborted (/Users/giovanni/Documents/Progetti/authenticator-web/node_modules/raw-body/index.js:269:10)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at abortIncoming (_http_server.js:284:11)
    at Socket.serverSocketCloseListener (_http_server.js:297:5)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:501:12)
```

I'm using 
```
ember-cli: 2.9.1
node: 7.0.0
os: darwin x64
```

**Comment by kellyselden** [comment]
This is old and doesn't seem to be an issue anymore. If anyone comes across this, please file a new issue against the most recent version.
